## Tesnsorflow 2.0 Alpha

### Usability

- tf.keras supported
- eager excution
- Still graph-based for optimization

In [43]:
import tensorflow as tf
print(tf.add(2,3))

tf.Tensor(5, shape=(), dtype=int32)


In [7]:
tf.__version__

'2.0.0-alpha0'

#### Flexibility

- Full lower-level API
- Internal ops accesible in tf.raw_ops
- Inheritable interfaces for variables, checkpoints, layers

### Upgrade

- Remove tf.contrib -> tf.compat.v1
- Conversion script: tf_upgrade_v2

## Timeline

![Imgur](https://i.imgur.com/mxMcNWh.png)

## Highlevel API

- TF.Keras

In [44]:
import tensorflow as tf
from tensorflow.keras import layers

print(tf.__version__)
print(tf.keras.__version__)

2.0.0-alpha0
2.2.4-tf


In [48]:
model = tf.keras.Sequential([
# Adds a densely-connected layer with 64 units to the model:
layers.Dense(64, activation='relu', input_shape=(32,)),
# Add another:
layers.Dense(64, activation='relu'),
# Add a softmax layer with 10 output units:
layers.Dense(10, activation='softmax')])

model.compile(optimizer="adam",
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [49]:
dataset = tf.data.Dataset.from_tensor_slices((data, labels))
dataset = dataset.batch(32).repeat()

In [50]:
for row in dataset.take(3):
    print(row)

(<tf.Tensor: id=12387, shape=(32, 32), dtype=float64, numpy=
array([[0.40824196, 0.04736897, 0.6718085 , ..., 0.51796181, 0.22758915,
        0.43086146],
       [0.43630371, 0.58804458, 0.56644841, ..., 0.95700153, 0.03178356,
        0.72922952],
       [0.46845909, 0.23423067, 0.25070465, ..., 0.93593286, 0.83366352,
        0.63784174],
       ...,
       [0.68023343, 0.7152207 , 0.59605146, ..., 0.86510799, 0.21099959,
        0.55887777],
       [0.51359554, 0.74050666, 0.86407331, ..., 0.34788666, 0.58518411,
        0.44705127],
       [0.52686712, 0.43246217, 0.37264317, ..., 0.85680559, 0.48761827,
        0.42422877]])>, <tf.Tensor: id=12388, shape=(32, 10), dtype=float64, numpy=
array([[0.22901111, 0.44884469, 0.2205335 , 0.70197929, 0.42550482,
        0.18585142, 0.45763803, 0.46708645, 0.77449022, 0.71784899],
       [0.85049162, 0.03465974, 0.50780375, 0.51079201, 0.3081847 ,
        0.50604792, 0.51294557, 0.82929919, 0.8058119 , 0.06316843],
       [0.30316333, 0.4316

In [51]:
val_dataset = tf.data.Dataset.from_tensor_slices((val_data, val_labels))
val_dataset = val_dataset.batch(32).repeat()

model.fit(dataset, epochs=10, steps_per_epoch=30,
          validation_data=val_dataset,
          validation_steps=3)

W0313 11:20:30.217071 140442727798592 training_utils.py:1353] Expected a shuffled dataset but input dataset `x` is not shuffled. Please invoke `shuffle()` on input dataset.


Epoch 1/10
30/30 [==============================] - 0s 11ms/step - loss: 12.1188 - accuracy: 0.1125 - val_loss: 13.9388 - val_accuracy: 0.1354
Epoch 2/10
30/30 [==============================] - 0s 1ms/step - loss: 18.6730 - accuracy: 0.1122 - val_loss: 27.8451 - val_accuracy: 0.0521
Epoch 3/10
30/30 [==============================] - 0s 1ms/step - loss: 39.3720 - accuracy: 0.1100 - val_loss: 55.5919 - val_accuracy: 0.0833
Epoch 4/10
30/30 [==============================] - 0s 1ms/step - loss: 71.5382 - accuracy: 0.1026 - val_loss: 92.9905 - val_accuracy: 0.0833
Epoch 5/10
30/30 [==============================] - 0s 1ms/step - loss: 114.4965 - accuracy: 0.1100 - val_loss: 143.6468 - val_accuracy: 0.0833
Epoch 6/10
30/30 [==============================] - 0s 1ms/step - loss: 174.9548 - accuracy: 0.0972 - val_loss: 213.8898 - val_accuracy: 0.1042
Epoch 7/10
30/30 [==============================] - 0s 1ms/step - loss: 249.8107 - accuracy: 0.0940 - val_loss: 295.5101 - val_accuracy: 0.0938

In [52]:
data = np.random.random((1000, 32))
labels = np.random.random((1000, 10))

model.evaluate(data, labels, batch_size=32)

model.evaluate(dataset, steps=30)

30/30 [==============================] - 0s 631us/step - loss: 527.7831 - accuracy: 0.0875


[527.7830729166667, 0.0875]

In [53]:
model = tf.keras.Sequential([layers.Dense(10,activation='softmax'),
                          layers.Dense(10,activation='softmax')])

model.compile(optimizer=tf.optimizers.RMSprop(0.001),
              loss='categorical_crossentropy',
              metrics=['accuracy'])

estimator = tf.keras.estimator.model_to_estimator(model)

W0313 11:20:54.964299 140442727798592 estimator.py:1799] Using temporary folder as model directory: /tmp/tmpl7ezec6e


In [27]:
estimator

![Imgur](https://i.imgur.com/Y80MT5M.png)

![Imgur](https://i.imgur.com/BM5Zwl6.png)

## Graph & Eager execution

In [54]:
@tf.function
def add(a,b):
    return a + b

add

In [55]:
add(tf.ones([2,2]), tf.ones([2,2]))

<tf.Tensor: id=16933, shape=(2, 2), dtype=float32, numpy=
array([[2., 2.],
       [2., 2.]], dtype=float32)>

In [56]:
a = tf.Variable(1.0)
b = tf.Variable(2.0)

@tf.function
def add(x,y):
    a.assign(y*b)
    b.assign_add(x*a)
    print(a,b)
    return a + b

add(1.0,2.0)

<tf.Variable 'Variable:0' shape=() dtype=float32> <tf.Variable 'Variable:0' shape=() dtype=float32>


<tf.Tensor: id=16966, shape=(), dtype=float32, numpy=10.0>

In [57]:
@tf.function
def f(x):
    while tf.reduce_sum(x) > 1:
        x=tf.tanh(x)
    return x

f(tf.random.uniform([10]))

<tf.Tensor: id=17010, shape=(10,), dtype=float32, numpy=
array([0.10166265, 0.1033851 , 0.09045415, 0.10055217, 0.1038611 ,
       0.09871371, 0.10168206, 0.09335323, 0.09990627, 0.10427355],
      dtype=float32)>

In [58]:
tf.random.uniform([10])

<tf.Tensor: id=17018, shape=(10,), dtype=float32, numpy=
array([0.42666185, 0.7630999 , 0.82865846, 0.7256645 , 0.4756503 ,
       0.19007206, 0.05505502, 0.27983236, 0.3975122 , 0.1119889 ],
      dtype=float32)>

### TF.graph

- session.run
- tf.control_dependencies
- tf.global_variables_initialzer
- tf.cond, tf.while_loop
- tf_function(+)

<tf.Tensor: id=2, shape=(), dtype=int32, numpy=5>